train: ./train/images
val: ./valid/images
test: ./test/images

nc: 3  # number of classes
names: ['key', 'book', 'cube']  # names of the classes

# YOLOv5-specific parameters
model:
  input_size: 640
  anchors:
    - [10, 13, 16, 30, 33, 23]
    - [30, 61, 62, 45, 59, 119]
    - [116, 90, 156, 198, 373, 326]
  strides: [8, 16, 32]